#!/usr/bin/env npx tsx
/**
 * Backup Restoration Script
 *
 * Downloads an encrypted backup from R2, decrypts it, verifies integrity,
 * and outputs either JSON or SQL INSERT statements for re-import into D1.
 *
 * Usage:
 *   ENCRYPTION_KEY=<64-char-hex> npx tsx scripts/restore.ts \
 *     --key backups/daily/2024-03-15.json.enc \
 *     --output ./restored.json \
 *     --format json
 *
 * Requirements: 18.3
 */

import { writeFileSync } from 'fs';

// ─── CLI argument parsing ─────────────────────────────────────────────────────

function parseArgs(argv: string[]): {
  key: string;
  output: string | null;
  format: 'json' | 'sql';
  verifyOnly: boolean;
  bucketName: string;
  accountId: string;
} {
  const args: Record<string, string> = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      args[argv[i].slice(2)] = argv[i + 1] ?? 'true';
      i++;
    }
  }

  if (!args['key']) {
    console.error('Error: --key is required (e.g. backups/daily/2024-03-15.json.enc)');
    process.exit(1);
  }

  return {
    key: args['key'],
    output: args['output'] ?? null,
    format: (args['format'] as 'json' | 'sql') ?? 'json',
    verifyOnly: args['verify'] === 'true',
    bucketName: args['bucket'] ?? 'financial-backups',
    accountId: args['account-id'] ?? process.env['CLOUDFLARE_ACCOUNT_ID'] ?? '',
  };
}

// ─── Crypto helpers (Node.js Web Crypto) ─────────────────────────────────────

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}

async function decryptBackup(encryptedText: string, encryptionKey: string): Promise<string> {
  if (encryptionKey.length !== 64) {
    throw new Error('ENCRYPTION_KEY must be a 64-character hex string');
  }

  const parts = encryptedText.split(':');
  if (parts.length !== 2) {
    throw new Error('Invalid encrypted format. Expected <iv_hex>:<ciphertext_hex>');
  }

  const [ivHex, ciphertextHex] = parts;
  const iv = hexToBytes(ivHex);
  const ciphertextBytes = hexToBytes(ciphertextHex);
  const keyBytes = hexToBytes(encryptionKey);

  const cryptoKey = await crypto.subtle.importKey(
    'raw',
    keyBytes,
    { name: 'AES-GCM', length: 256 },
    false,
    ['decrypt']
  );

  const plaintextBuffer = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv, tagLength: 128 },
    cryptoKey,
    ciphertextBytes
  );

  return new TextDecoder().decode(plaintextBuffer);
}

// ─── Payload types ────────────────────────────────────────────────────────────

interface BackupPayload {
  version: string;
  timestamp: string;
  tables: Record<string, Record<string, unknown>[]>;
}

// ─── Integrity verification ───────────────────────────────────────────────────

function verifyPayload(payload: BackupPayload): {
  valid: boolean;
  recordCount: number;
  tables: Record<string, number>;
  errors: string[];
} {
  const errors: string[] = [];

  if (!payload.version) errors.push('Missing version field');
  if (!payload.timestamp) errors.push('Missing timestamp field');
  if (!payload.tables || typeof payload.tables !== 'object') errors.push('Missing or invalid tables field');

  if (errors.length > 0) {
    return { valid: false, recordCount: 0, tables: {}, errors };
  }

  const tables: Record<string, number> = {};
  let recordCount = 0;

  for (const [tableName, rows] of Object.entries(payload.tables)) {
    if (!Array.isArray(rows)) {
      errors.push(`Table "${tableName}" is not an array`);
      continue;
    }
    tables[tableName] = rows.length;
    recordCount += rows.length;
  }

  return { valid: errors.length === 0, recordCount, tables, errors };
}

// ─── SQL generation ───────────────────────────────────────────────────────────

function generateSQL(payload: BackupPayload): string {
  const lines: string[] = [
    '-- Restoration SQL generated by restore.ts',
    `-- Backup timestamp: ${payload.timestamp}`,
    `-- Backup version: ${payload.version}`,
    '',
    'PRAGMA foreign_keys = OFF;',
    'BEGIN TRANSACTION;',
    '',
  ];

  for (const [tableName, rows] of Object.entries(payload.tables)) {
    if (!Array.isArray(rows) || rows.length === 0) continue;

    lines.push(`-- Table: ${tableName} (${rows.length} rows)`);
    lines.push(`DELETE FROM ${tableName};`);

    for (const row of rows) {
      const columns = Object.keys(row);
      const values = columns.map((col) => {
        const val = row[col];
        if (val === null || val === undefined) return 'NULL';
        if (typeof val === 'number') return String(val);
        if (typeof val === 'boolean') return val ? '1' : '0';
        // Escape single quotes in strings
        return `'${String(val).replace(/'/g, "''")}'`;
      });
      lines.push(`INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')});`);
    }
    lines.push('');
  }

  lines.push('COMMIT;');
  lines.push('PRAGMA foreign_keys = ON;');

  return lines.join('\n');
}

// ─── R2 download via Cloudflare API ──────────────────────────────────────────

async function downloadFromR2(
  bucketName: string,
  key: string,
  accountId: string,
  apiToken: string
): Promise<string> {
  const url = `https://api.cloudflare.com/client/v4/accounts/${accountId}/r2/buckets/${bucketName}/objects/${encodeURIComponent(key)}`;

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${apiToken}`,
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to download backup: ${response.status} ${response.statusText}`);
  }

  return response.text();
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv);

  const encryptionKey = process.env['ENCRYPTION_KEY'] ?? '';
  if (!encryptionKey) {
    console.error('Error: ENCRYPTION_KEY environment variable is required');
    process.exit(1);
  }

  const apiToken = process.env['CLOUDFLARE_API_TOKEN'] ?? '';
  if (!apiToken && !args.verifyOnly) {
    console.error('Error: CLOUDFLARE_API_TOKEN environment variable is required for download');
    console.error('Set it with: export CLOUDFLARE_API_TOKEN=<your-token>');
    process.exit(1);
  }

  console.log(`\n[restore] Downloading backup: ${args.key}`);
  console.log(`[restore] Bucket: ${args.bucketName}`);

  // 1. Download
  let encryptedText: string;
  try {
    encryptedText = await downloadFromR2(args.bucketName, args.key, args.accountId, apiToken);
    console.log(`[restore] Downloaded ${encryptedText.length} characters`);
  } catch (err) {
    console.error('[restore] Download failed:', err instanceof Error ? err.message : err);
    process.exit(1);
  }

  // 2. Decrypt
  let plaintext: string;
  try {
    plaintext = await decryptBackup(encryptedText, encryptionKey);
    console.log('[restore] Decryption successful');
  } catch (err) {
    console.error('[restore] Decryption failed:', err instanceof Error ? err.message : err);
    process.exit(1);
  }

  // 3. Parse
  let payload: BackupPayload;
  try {
    payload = JSON.parse(plaintext) as BackupPayload;
  } catch {
    console.error('[restore] Failed to parse backup JSON');
    process.exit(1);
  }

  // 4. Verify integrity
  const verification = verifyPayload(payload);
  console.log('\n[restore] Integrity verification:');
  console.log(`  Valid:        ${verification.valid}`);
  console.log(`  Timestamp:    ${payload.timestamp}`);
  console.log(`  Version:      ${payload.version}`);
  console.log(`  Total rows:   ${verification.recordCount}`);
  console.log('  Tables:');
  for (const [table, count] of Object.entries(verification.tables)) {
    console.log(`    ${table.padEnd(25)} ${count} rows`);
  }

  if (!verification.valid) {
    console.error('\n[restore] Integrity check FAILED:');
    for (const err of verification.errors) {
      console.error(`  - ${err}`);
    }
    process.exit(1);
  }

  if (args.verifyOnly) {
    console.log('\n[restore] Verification complete. No output file written (--verify mode).');
    process.exit(0);
  }

  // 5. Write output
  if (!args.output) {
    console.error('Error: --output is required unless using --verify');
    process.exit(1);
  }

  let outputContent: string;
  if (args.format === 'sql') {
    outputContent = generateSQL(payload);
    console.log(`\n[restore] Generated SQL with ${outputContent.split('\n').length} lines`);
  } else {
    outputContent = JSON.stringify(payload, null, 2);
  }

  writeFileSync(args.output, outputContent, 'utf-8');
  console.log(`\n[restore] Output written to: ${args.output}`);
  console.log('[restore] Restoration complete.');

  if (args.format === 'sql') {
    console.log('\nTo apply the SQL:');
    console.log(`  wrangler d1 execute financial-transparency-db --local --file ${args.output}`);
    console.log(`  wrangler d1 execute financial-transparency-db --file ${args.output}  # remote`);
  }
}

main().catch((err) => {
  console.error('[restore] Unexpected error:', err);
  process.exit(1);
});
